### ISSUE TITLE
Color 0: Invalid hex code

### ISSUE THREAD

**Issue by Username-Cant-Be-Blank** [evanpurkhiser/linux-vt-setcolors#11]
I'm getting `Color 0: Invalid hex code` with every color I've ever tried.
I'm running `setcolors -c /dev/tty2 /etc/vconsole.conf`
and my config file is
```
KEYMAP=us
FONT=ter-118n
COLOR_0=DE0049

```
package version: etcolors-git 69.7e90c8e-1 from AUR

**Comment by GaKu999** [comment]
Use lowercase for the hexcodes...

**Comment by GaKu999** [comment]
Disregard, vconsole.conf is used by the mkinitcio hook, setcolors uses a diferencia format entirely...

**Comment by Username-Cant-Be-Blank** [comment]
fixed by changing to lowercase, specifying the color that the hex code replaces, and having more than one color entry.
I changed
```
KEYMAP=us
FONT=ter-118n
COLOR_0=DE0049
```
to
```
KEYMAP=us
FONT=ter-118n
0#de0049    base03
1#dc322f    red
```
