### ISSUE TITLE
"Color 0: invalid color" during early boot

### ISSUE THREAD

**Issue by ohnonot** [EvanPurkhiser/linux-vt-setcolors#7]
in about 90% of all cases, i would get this error message during early boot and the colorscheme would not be applied to the tty.
the weirdest thing, every now and then it WOULD work.
This is on archlinux.
no errors during `mkinitcpio -p linux-lts` (which I always run after every change to /etc/vconsole.conf).
the position of the `color` hook in /etc/mkinitcpio.conf does not seem to matter (tried first and last).

testing various color schemes, it seems that this happens when Color_0 starts with or contains a 0 (zero), e.g. "COLOR_0=090300" - changing that to "COLOR_0=100300" fixes the problem.
but the color "000000" does not trigger the error.
it also seems that *only* COLOR_0 triggers the error, and it doesn't matter whether it comes first in /etc/vconsole.conf or not.

right now, I'm using atelierdune.dark color scheme from the examples in the github repo, but i had to change the first color (20201d) to make it work.
my /etc/vconsole.conf looks like this:
```
KEYMAP=fi
FONT=ter-powerline-v16n

COLOR_0=1F1F1F
COLOR_1=d73737
COLOR_2=60ac39
COLOR_3=cfb017
COLOR_4=6684e1
COLOR_5=b854d4
COLOR_6=1fad83
COLOR_7=a6a28c
COLOR_8=7d7a68
COLOR_9=d73737
COLOR_10=60ac39
COLOR_11=cfb017
COLOR_12=6684e1
COLOR_13=b854d4
COLOR_14=1fad83
COLOR_15=fefbec
```

**Comment by ohnonot** [comment]
i was barking up the wrong tree.

i may have found something in /usr/lib/initcpio/install/colors - the COLORS variable is *not* initialized with an empty string.

after adding this:

```
diff -c /usr/lib/initcpio/install/colors /usr/lib/initcpio/install/colors-new
*** /usr/lib/initcpio/install/colors	2017-09-11 20:13:44.186328524 +0300
--- /usr/lib/initcpio/install/colors-new	2017-09-11 20:13:03.097470560 +0300
***************
*** 3,9 ****
      # subshell to avoid namespace pollution
      (
          [[ -s /etc/vconsole.conf ]] && . /etc/vconsole.conf
! 		
          for COLOR_ID in $(seq 0 15)
          do
              COLOR=$(eval "echo \$COLOR_${COLOR_ID}")
--- 3,11 ----
      # subshell to avoid namespace pollution
      (
          [[ -s /etc/vconsole.conf ]] && . /etc/vconsole.conf
! 
!         COLORS=""
! 
          for COLOR_ID in $(seq 0 15)
          do
              COLOR=$(eval "echo \$COLOR_${COLOR_ID}")
***************
*** 24,30 ****
      add_runscript
      add_binary "/usr/bin/setcolors"
  }
! 	
  help() {
      cat <<HELPEOF
  This hook will setup the console colors during early user space.
--- 26,32 ----
      add_runscript
      add_binary "/usr/bin/setcolors"
  }
! 
  help() {
      cat <<HELPEOF
  This hook will setup the console colors during early user space.
```

(some noise in that diff because i removed "empty" tabs as well; the only relevant thing is COLORS="")

i tested with about ten different color schemes, and could not reproduce the issue.
proof: removing that line again, rebuild the initrd, and immediately the error "color 0: invalid color" is there again (and no color scheme applied).

**Comment by EvanPurkhiser** [comment]
Any chance I could convince you to open a PR over here https://github.com/EvanPurkhiser/mkinitcpio-colors/blob/master/install/colors ? :-)

**Comment by ohnonot** [comment]
oops!
https://github.com/EvanPurkhiser/mkinitcpio-colors/issues/3
